import { PrismaClient } from '@prisma/client';
import * as bcryptjs from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  const adminPassword = await bcryptjs.hash('Nwrah@123', 12);
  const admin = await prisma.user.upsert({
    where: { email: 'nwrah3647@gmail.com' },
    update: {},
    create: {
      email: 'nwrah3647@gmail.com',
      passwordHash: adminPassword,
      name: 'نورة القحطاني',
      role: 'SUPER_ADMIN',
      emailVerified: true,
    },
  });

  const guest = await prisma.user.upsert({
    where: { email: 'guest@reportify.app' },
    update: {},
    create: {
      email: 'guest@reportify.app',
      name: 'زائر',
      role: 'USER',
      emailVerified: true,
    },
  });

  const templates = [
    {
      name: 'business-report-modern-blue',
      nameAr: 'تقرير أعمال - أزرق عصري',
      description: 'Professional business report template with modern blue design',
      descriptionAr: 'قالب تقرير أعمال احترافي بتصميم أزرق عصري',
      category: 'تقارير الأعمال',
      thumbnailUrl: '/templates/business-blue.png',
      templateData: JSON.stringify({ layout: 'modern', sections: ['header', 'executive-summary', 'content', 'charts', 'footer'], styles: { primary: '#1E3A5F', secondary: '#3498DB', accent: '#2ECC71' } }),
      colors: JSON.stringify({ primary: '#1E3A5F', secondary: '#3498DB', accent: '#2ECC71', background: '#FFFFFF', text: '#2C3E50' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'corporate-brochure-minimal',
      nameAr: 'بروشور شركة - مينيمال',
      description: 'Clean and minimal corporate brochure template',
      descriptionAr: 'قالب بروشور شركة نظيف ومينيمالي',
      category: 'بروشورات تجارية',
      thumbnailUrl: '/templates/brochure-minimal.png',
      templateData: JSON.stringify({ layout: 'tri-fold', sections: ['cover', 'about', 'services', 'contact'], styles: { primary: '#2C3E50', secondary: '#7F8C8D', accent: '#E74C3C' } }),
      colors: JSON.stringify({ primary: '#2C3E50', secondary: '#7F8C8D', accent: '#E74C3C', background: '#ECF0F1', text: '#2C3E50' }),
      fonts: JSON.stringify({ heading: 'Tajawal', body: 'Almarai' }),
      isPublished: true,
    },
    {
      name: 'academic-report-university',
      nameAr: 'تقرير أكاديمي - جامعة',
      description: 'Formal academic report template for universities',
      descriptionAr: 'قالب تقرير أكاديمي رسمي مناسب للجامعات',
      category: 'تقارير جامعية',
      thumbnailUrl: '/templates/academic-formal.png',
      templateData: JSON.stringify({ layout: 'classic', sections: ['cover', 'abstract', 'introduction', 'methodology', 'results', 'discussion', 'references'], styles: { primary: '#8B0000', secondary: '#DAA520', accent: '#333333' } }),
      colors: JSON.stringify({ primary: '#8B0000', secondary: '#DAA520', accent: '#333333', background: '#FFFFF8', text: '#333333' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'marketing-brochure-vibrant',
      nameAr: 'بروشور تسويقي - زاهي',
      description: 'Eye-catching marketing brochure with vibrant colors',
      descriptionAr: 'بروشور تسويقي جذاب بألوان زاهية',
      category: 'بروشورات تسويقية',
      thumbnailUrl: '/templates/marketing-vibrant.png',
      templateData: JSON.stringify({ layout: 'modern', sections: ['hero', 'features', 'testimonials', 'cta'], styles: { primary: '#FF6B35', secondary: '#F7C59F', accent: '#004E89' } }),
      colors: JSON.stringify({ primary: '#FF6B35', secondary: '#F7C59F', accent: '#004E89', background: '#FFFFFF', text: '#1A1A2E' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'cv-professional',
      nameAr: 'سيرة ذاتية - احترافية',
      description: 'Professional CV template for job applications',
      descriptionAr: 'قالب سيرة ذاتية احترافي للتقديم على الوظائف',
      category: 'سير ذاتية',
      thumbnailUrl: '/templates/cv-professional.png',
      templateData: JSON.stringify({ layout: 'two-column', sections: ['header', 'summary', 'experience', 'education', 'skills', 'certifications'], styles: { primary: '#2C3E50', secondary: '#3498DB', accent: '#27AE60' } }),
      colors: JSON.stringify({ primary: '#2C3E50', secondary: '#3498DB', accent: '#27AE60', background: '#FFFFFF', text: '#2C3E50' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'company-premium-profile',
      nameAr: 'ملف شركة - بريميوم',
      description: 'Premium company profile with elegant design',
      descriptionAr: 'ملف تعريف شركة بريميوم بتصميم أنيق',
      category: 'ملفات شركات',
      thumbnailUrl: '/templates/company-premium.png',
      templateData: JSON.stringify({ layout: 'premium', sections: ['cover', 'about', 'vision-mission', 'team', 'services', 'achievements', 'contact'], styles: { primary: '#1A1A2E', secondary: '#16213E', accent: '#E94560' } }),
      colors: JSON.stringify({ primary: '#1A1A2E', secondary: '#16213E', accent: '#E94560', background: '#FFFFFF', text: '#1A1A2E' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'educational-report-kids',
      nameAr: 'تقرير تعليمي - أطفال',
      description: 'Fun and colorful educational report for children',
      descriptionAr: 'قالب تقرير تعليمي مرح وملون للأطفال',
      category: 'تقارير تعليمية',
      thumbnailUrl: '/templates/educational-kids.png',
      templateData: JSON.stringify({ layout: 'playful', sections: ['header', 'content', 'activities', 'achievements', 'footer'], styles: { primary: '#FF6B6B', secondary: '#4ECDC4', accent: '#FFE66D' } }),
      colors: JSON.stringify({ primary: '#FF6B6B', secondary: '#4ECDC4', accent: '#FFE66D', background: '#FFF9E6', text: '#2C3E50' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'financial-report-dark',
      nameAr: 'تقرير مالي - داكن',
      description: 'Modern financial report with dark theme',
      descriptionAr: 'تقرير مالي حديث بتصميم داكن',
      category: 'تقارير مالية',
      thumbnailUrl: '/templates/financial-dark.png',
      templateData: JSON.stringify({ layout: 'modern', sections: ['summary', 'revenue', 'expenses', 'projections', 'charts'], styles: { primary: '#0F0F0F', secondary: '#1A1A2E', accent: '#00D2FF' } }),
      colors: JSON.stringify({ primary: '#0F0F0F', secondary: '#1A1A2E', accent: '#00D2FF', background: '#1A1A2E', text: '#FFFFFF' }),
      fonts: JSON.stringify({ heading: 'Tajawal', body: 'Almarai' }),
      isPublished: true,
    },
    {
      name: 'hr-report-clean',
      nameAr: 'تقرير موارد بشرية - نظيف',
      description: 'Clean and organized HR report template',
      descriptionAr: 'قالب تقرير موارد بشرية نظيف ومنظم',
      category: 'تقارير موارد بشرية',
      thumbnailUrl: '/templates/hr-clean.png',
      templateData: JSON.stringify({ layout: 'clean', sections: ['overview', 'headcount', 'attendance', 'performance', 'recruitment'], styles: { primary: '#6C5CE7', secondary: '#A29BFE', accent: '#00B894' } }),
      colors: JSON.stringify({ primary: '#6C5CE7', secondary: '#A29BFE', accent: '#00B894', background: '#FFFFFF', text: '#2D3436' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'technical-report-developer',
      nameAr: 'تقرير تقني - مطورين',
      description: 'Technical documentation and report for developers',
      descriptionAr: 'قالب تقرير وتوثيق تقني للمطورين',
      category: 'تقارير تقنية',
      thumbnailUrl: '/templates/technical-dev.png',
      templateData: JSON.stringify({ layout: 'technical', sections: ['title', 'overview', 'architecture', 'implementation', 'testing', 'deployment', 'appendix'], styles: { primary: '#282A36', secondary: '#44475A', accent: '#50FA7B' } }),
      colors: JSON.stringify({ primary: '#282A36', secondary: '#44475A', accent: '#50FA7B', background: '#282A36', text: '#F8F8F2' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'presentation-corporate',
      nameAr: 'عرض تقديمي - شركات',
      description: 'Professional corporate presentation template',
      descriptionAr: 'قالب عرض تقديمي احترافي للشركات',
      category: 'عروض تقديمية',
      thumbnailUrl: '/templates/presentation-corporate.png',
      templateData: JSON.stringify({ layout: 'slides', sections: ['title', 'agenda', 'content', 'data', 'conclusion'], styles: { primary: '#003366', secondary: '#0066CC', accent: '#FF6600' } }),
      colors: JSON.stringify({ primary: '#003366', secondary: '#0066CC', accent: '#FF6600', background: '#FFFFFF', text: '#333333' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'product-brochure-modern',
      nameAr: 'بروشور منتج - عصري',
      description: 'Modern product brochure with clean showcase',
      descriptionAr: 'بروشور منتج عصري مع عرض منتجات أنيق',
      category: 'عروض منتجات',
      thumbnailUrl: '/templates/product-brochure.png',
      templateData: JSON.stringify({ layout: 'grid', sections: ['hero', 'features', 'specs', 'pricing', 'cta'], styles: { primary: '#2D3436', secondary: '#636E72', accent: '#FDCB6E' } }),
      colors: JSON.stringify({ primary: '#2D3436', secondary: '#636E72', accent: '#FDCB6E', background: '#FFFFFF', text: '#2D3436' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'academic-research-paper',
      nameAr: 'ورقة بحثية أكاديمية',
      description: 'Formal academic research paper with IMRAD structure',
      descriptionAr: 'قالب ورقة بحثية أكاديمية رسمية بهيكل IMRAD',
      category: 'تقارير جامعية',
      thumbnailUrl: '/templates/academic-research.png',
      templateData: JSON.stringify({ layout: 'academic', sections: ['title', 'abstract', 'introduction', 'methodology', 'results', 'discussion', 'references'], styles: { primary: '#1B1B2F', secondary: '#162447', accent: '#E43F5A' } }),
      colors: JSON.stringify({ primary: '#1B1B2F', secondary: '#162447', accent: '#E43F5A', background: '#FFFFFF', text: '#1B1B2F' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'marketing-plan-strategic',
      nameAr: 'خطة تسويقية - استراتيجية',
      description: 'Comprehensive marketing plan with SWOT and KPIs',
      descriptionAr: 'قالب خطة تسويقية شاملة مع تحليل SWOT',
      category: 'تقارير تسويق',
      thumbnailUrl: '/templates/marketing-strategic.png',
      templateData: JSON.stringify({ layout: 'strategic', sections: ['executive-summary', 'market-analysis', 'swot', 'objectives', 'channels', 'budget', 'kpis'], styles: { primary: '#0D47A1', secondary: '#1976D2', accent: '#FF6F00' } }),
      colors: JSON.stringify({ primary: '#0D47A1', secondary: '#1976D2', accent: '#FF6F00', background: '#FFFFFF', text: '#212121' }),
      fonts: JSON.stringify({ heading: 'Tajawal', body: 'Almarai' }),
      isPublished: true,
    },
    {
      name: 'report-sales-quarterly',
      nameAr: 'تقرير مبيعات ربع سنوي',
      description: 'Quarterly sales report with charts and analytics',
      descriptionAr: 'تقرير مبيعات ربع سنوي مع رسوم بيانية وتحليلات',
      category: 'تقارير الأعمال',
      thumbnailUrl: '/templates/sales-quarterly.png',
      templateData: JSON.stringify({ layout: 'analytics', sections: ['summary', 'revenue', 'channels', 'products', 'forecast'], styles: { primary: '#00695C', secondary: '#26A69A', accent: '#FF8A65' } }),
      colors: JSON.stringify({ primary: '#00695C', secondary: '#26A69A', accent: '#FF8A65', background: '#FFFFFF', text: '#263238' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'brochure-real-estate',
      nameAr: 'بروشور عقاري',
      description: 'Elegant real estate property brochure',
      descriptionAr: 'بروشور عقاري أنيق لعرض العقارات',
      category: 'بروشورات تجارية',
      thumbnailUrl: '/templates/real-estate.png',
      templateData: JSON.stringify({ layout: 'premium', sections: ['cover', 'property', 'gallery', 'location', 'contact'], styles: { primary: '#2C1810', secondary: '#8D6E63', accent: '#FFD54F' } }),
      colors: JSON.stringify({ primary: '#2C1810', secondary: '#8D6E63', accent: '#FFD54F', background: '#FFF8E1', text: '#3E2723' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'report-project-management',
      nameAr: 'تقرير إدارة مشاريع',
      description: 'Project management status report template',
      descriptionAr: 'قالب تقرير حالة مشروع لإدارة المشاريع',
      category: 'تقارير مشاريع',
      thumbnailUrl: '/templates/project-mgmt.png',
      templateData: JSON.stringify({ layout: 'dashboard', sections: ['summary', 'timeline', 'tasks', 'resources', 'risks', 'milestones'], styles: { primary: '#1565C0', secondary: '#42A5F5', accent: '#FFA726' } }),
      colors: JSON.stringify({ primary: '#1565C0', secondary: '#42A5F5', accent: '#FFA726', background: '#FFFFFF', text: '#1A237E' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'presentation-startup-pitch',
      nameAr: 'عرض تقديمي - شركة ناشئة',
      description: 'Startup pitch deck presentation template',
      descriptionAr: 'قالب عرض تقديمي للشركات الناشئة',
      category: 'عروض تقديمية',
      thumbnailUrl: '/templates/startup-pitch.png',
      templateData: JSON.stringify({ layout: 'pitch', sections: ['title', 'problem', 'solution', 'market', 'business-model', 'team', 'financials'], styles: { primary: '#6200EA', secondary: '#B388FF', accent: '#1DE9B6' } }),
      colors: JSON.stringify({ primary: '#6200EA', secondary: '#B388FF', accent: '#1DE9B6', background: '#FFFFFF', text: '#212121' }),
      fonts: JSON.stringify({ heading: 'Tajawal', body: 'Almarai' }),
      isPublished: true,
    },
    {
      name: 'cv-creative-designer',
      nameAr: 'سيرة ذاتية - مبدعين',
      description: 'Creative CV template for designers and artists',
      descriptionAr: 'قالب سيرة ذاتية إبداعية للمصممين والفنانين',
      category: 'سير ذاتية',
      thumbnailUrl: '/templates/cv-creative.png',
      templateData: JSON.stringify({ layout: 'creative', sections: ['header', 'about', 'portfolio', 'skills', 'experience', 'education'], styles: { primary: '#E91E63', secondary: '#F06292', accent: '#00BCD4' } }),
      colors: JSON.stringify({ primary: '#E91E63', secondary: '#F06292', accent: '#00BCD4', background: '#FAFAFA', text: '#212121' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'report-environmental-impact',
      nameAr: 'تقرير الأثر البيئي',
      description: 'Environmental impact assessment report',
      descriptionAr: 'تقرير تقييم الأثر البيئي مع تحليلات',
      category: 'تقارير الأعمال',
      thumbnailUrl: '/templates/environmental.png',
      templateData: JSON.stringify({ layout: 'formal', sections: ['cover', 'executive-summary', 'methodology', 'findings', 'recommendations', 'references'], styles: { primary: '#2E7D32', secondary: '#66BB6A', accent: '#1B5E20' } }),
      colors: JSON.stringify({ primary: '#2E7D32', secondary: '#66BB6A', accent: '#1B5E20', background: '#F1F8E9', text: '#1B5E20' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'brochure-restaurant-menu',
      nameAr: 'بروشور مطعم - قائمة طعام',
      description: 'Elegant restaurant menu and brochure template',
      descriptionAr: 'قالب بروشور مطعم أنيق لعرض قوائم الطعام',
      category: 'بروشورات تسويقية',
      thumbnailUrl: '/templates/restaurant-menu.png',
      templateData: JSON.stringify({ layout: 'menu', sections: ['cover', 'appetizers', 'main-course', 'desserts', 'beverages'], styles: { primary: '#5D4037', secondary: '#A1887F', accent: '#FFAB00' } }),
      colors: JSON.stringify({ primary: '#5D4037', secondary: '#A1887F', accent: '#FFAB00', background: '#FFF8E1', text: '#3E2723' }),
      fonts: JSON.stringify({ heading: 'Tajawal', body: 'Almarai' }),
      isPublished: true,
    },
    {
      name: 'report-it-security-audit',
      nameAr: 'تقرير أمن معلومات - تدقيق',
      description: 'IT security audit report template',
      descriptionAr: 'قالب تقرير تدقيق أمن المعلومات',
      category: 'تقارير تقنية',
      thumbnailUrl: '/templates/security-audit.png',
      templateData: JSON.stringify({ layout: 'audit', sections: ['title', 'scope', 'methodology', 'findings', 'vulnerabilities', 'recommendations', 'appendix'], styles: { primary: '#B71C1C', secondary: '#E53935', accent: '#FFB300' } }),
      colors: JSON.stringify({ primary: '#B71C1C', secondary: '#E53935', accent: '#FFB300', background: '#FFF8E1', text: '#212121' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'presentation-training-course',
      nameAr: 'عرض تقديمي - دورة تدريبية',
      description: 'Training course materials presentation',
      descriptionAr: 'قالب عرض تقديمي للمواد التدريبية',
      category: 'عروض تقديمية',
      thumbnailUrl: '/templates/training-course.png',
      templateData: JSON.stringify({ layout: 'educational', sections: ['title', 'objectives', 'content', 'examples', 'exercises', 'summary'], styles: { primary: '#00838F', secondary: '#4DD0E1', accent: '#FF8A65' } }),
      colors: JSON.stringify({ primary: '#00838F', secondary: '#4DD0E1', accent: '#FF8A65', background: '#FFFFFF', text: '#212121' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'cv-executive-management',
      nameAr: 'سيرة ذاتية - تنفيذي',
      description: 'Executive CV template for senior management',
      descriptionAr: 'قالب سيرة ذاتية تنفيذية للإدارة العليا',
      category: 'سير ذاتية',
      thumbnailUrl: '/templates/cv-executive.png',
      templateData: JSON.stringify({ layout: 'executive', sections: ['header', 'profile', 'career', 'achievements', 'education', 'references'], styles: { primary: '#1A237E', secondary: '#3949AB', accent: '#C5CAE9' } }),
      colors: JSON.stringify({ primary: '#1A237E', secondary: '#3949AB', accent: '#C5CAE9', background: '#FFFFFF', text: '#1A237E' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'report-market-research',
      nameAr: 'تقرير أبحاث سوق',
      description: 'Market research analysis report template',
      descriptionAr: 'قالب تقرير تحليل أبحاث السوق',
      category: 'تقارير تسويق',
      thumbnailUrl: '/templates/market-research.png',
      templateData: JSON.stringify({ layout: 'analysis', sections: ['executive-summary', 'methodology', 'demographics', 'competitors', 'findings', 'recommendations'], styles: { primary: '#4A148C', secondary: '#7B1FA2', accent: '#FF6F00' } }),
      colors: JSON.stringify({ primary: '#4A148C', secondary: '#7B1FA2', accent: '#FF6F00', background: '#F3E5F5', text: '#4A148C' }),
      fonts: JSON.stringify({ heading: 'Tajawal', body: 'Almarai' }),
      isPublished: true,
    },
    {
      name: 'brochure-travel-tourism',
      nameAr: 'بروشور سياحي',
      description: 'Travel and tourism brochure with destinations',
      descriptionAr: 'بروشور سياحي جذاب لعرض الوجهات',
      category: 'بروشورات تسويقية',
      thumbnailUrl: '/templates/travel-brochure.png',
      templateData: JSON.stringify({ layout: 'magazine', sections: ['cover', 'destinations', 'packages', 'gallery', 'booking'], styles: { primary: '#006064', secondary: '#00BCD4', accent: '#FF8F00' } }),
      colors: JSON.stringify({ primary: '#006064', secondary: '#00BCD4', accent: '#FF8F00', background: '#E0F7FA', text: '#006064' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'report-annual-business',
      nameAr: 'تقرير سنوي - أعمال',
      description: 'Annual business report with financial highlights',
      descriptionAr: 'تقرير سنوي للأعمال مع أبرز النتائج المالية',
      category: 'تقارير الأعمال',
      thumbnailUrl: '/templates/annual-report.png',
      templateData: JSON.stringify({ layout: 'premium', sections: ['cover', 'ceo-message', 'highlights', 'financials', 'operations', 'outlook'], styles: { primary: '#0D47A1', secondary: '#1565C0', accent: '#FFD700' } }),
      colors: JSON.stringify({ primary: '#0D47A1', secondary: '#1565C0', accent: '#FFD700', background: '#FFFFFF', text: '#212121' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'portfolio-photography',
      nameAr: 'معرض أعمال - مصورين',
      description: 'Photography portfolio template',
      descriptionAr: 'قالب معرض أعمال للمصورين الفوتوغرافيين',
      category: 'ملفات إنجاز',
      thumbnailUrl: '/templates/photo-portfolio.png',
      templateData: JSON.stringify({ layout: 'gallery', sections: ['cover', 'portfolio', 'about', 'services', 'contact'], styles: { primary: '#212121', secondary: '#616161', accent: '#FFFFFF' } }),
      colors: JSON.stringify({ primary: '#212121', secondary: '#616161', accent: '#FFFFFF', background: '#000000', text: '#FFFFFF' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'report-hr-performance',
      nameAr: 'تقرير أداء الموظفين',
      description: 'Employee performance review report',
      descriptionAr: 'تقرير تقييم أداء الموظفين السنوي',
      category: 'تقارير موارد بشرية',
      thumbnailUrl: '/templates/performance-review.png',
      templateData: JSON.stringify({ layout: 'evaluation', sections: ['employee-info', 'objectives', 'rating', 'comments', 'goals'], styles: { primary: '#37474F', secondary: '#78909C', accent: '#FFB300' } }),
      colors: JSON.stringify({ primary: '#37474F', secondary: '#78909C', accent: '#FFB300', background: '#FFFFFF', text: '#263238' }),
      fonts: JSON.stringify({ heading: 'Tajawal', body: 'Almarai' }),
      isPublished: true,
    },
    {
      name: 'presentation-product-launch',
      nameAr: 'عرض تقديمي - إطلاق منتج',
      description: 'Product launch presentation template',
      descriptionAr: 'قالب عرض تقديمي لإطلاق منتج جديد',
      category: 'عروض تقديمية',
      thumbnailUrl: '/templates/product-launch.png',
      templateData: JSON.stringify({ layout: 'launch', sections: ['title', 'problem', 'solution', 'features', 'roadmap', 'launch-plan'], styles: { primary: '#FF5722', secondary: '#FF8A65', accent: '#00BCD4' } }),
      colors: JSON.stringify({ primary: '#FF5722', secondary: '#FF8A65', accent: '#00BCD4', background: '#FFFFFF', text: '#212121' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'brochure-healthcare',
      nameAr: 'بروشور رعاية صحية',
      description: 'Healthcare services and clinic brochure',
      descriptionAr: 'بروشور خدمات رعاية صحية وعيادات',
      category: 'بروشورات تجارية',
      thumbnailUrl: '/templates/healthcare.png',
      templateData: JSON.stringify({ layout: 'clean', sections: ['cover', 'services', 'team', 'facilities', 'contact'], styles: { primary: '#00695C', secondary: '#4DB6AC', accent: '#B2DFDB' } }),
      colors: JSON.stringify({ primary: '#00695C', secondary: '#4DB6AC', accent: '#B2DFDB', background: '#FFFFFF', text: '#004D40' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'report-business-plan',
      nameAr: 'خطة عمل - مشروع',
      description: 'Comprehensive business plan template',
      descriptionAr: 'قالب خطة عمل شاملة للمشاريع',
      category: 'تقارير الأعمال',
      thumbnailUrl: '/templates/business-plan.png',
      templateData: JSON.stringify({ layout: 'strategic', sections: ['cover', 'executive-summary', 'company', 'market', 'products', 'financials', 'appendix'], styles: { primary: '#263238', secondary: '#455A64', accent: '#607D8B' } }),
      colors: JSON.stringify({ primary: '#263238', secondary: '#455A64', accent: '#43A047', background: '#FFFFFF', text: '#212121' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'presentation-investor-deck',
      nameAr: 'عرض تقديمي - مستثمرين',
      description: 'Investor pitch deck for funding',
      descriptionAr: 'عرض تقديمي لجذب المستثمرين',
      category: 'عروض تقديمية',
      thumbnailUrl: '/templates/investor-deck.png',
      templateData: JSON.stringify({ layout: 'pitch', sections: ['title', 'problem', 'solution', 'traction', 'team', 'financials', 'ask'], styles: { primary: '#1B5E20', secondary: '#4CAF50', accent: '#8BC34A' } }),
      colors: JSON.stringify({ primary: '#1B5E20', secondary: '#4CAF50', accent: '#8BC34A', background: '#FFFFFF', text: '#212121' }),
      fonts: JSON.stringify({ heading: 'Tajawal', body: 'Almarai' }),
      isPublished: true,
    },
    {
      name: 'cv-fresh-graduate',
      nameAr: 'سيرة ذاتية - خريج جديد',
      description: 'CV template for fresh graduates',
      descriptionAr: 'قالب سيرة ذاتية للخريجين الجدد',
      category: 'سير ذاتية',
      thumbnailUrl: '/templates/cv-graduate.png',
      templateData: JSON.stringify({ layout: 'modern', sections: ['header', 'objective', 'education', 'projects', 'skills', 'activities'], styles: { primary: '#0277BD', secondary: '#29B6F6', accent: '#B3E5FC' } }),
      colors: JSON.stringify({ primary: '#0277BD', secondary: '#29B6F6', accent: '#B3E5FC', background: '#FFFFFF', text: '#01579B' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'report-school-grade',
      nameAr: 'كشف درجات مدرسي',
      description: 'School grade report and transcript template',
      descriptionAr: 'قالب كشف درجات وتقرير مدرسي',
      category: 'تقارير مدرسية',
      thumbnailUrl: '/templates/school-grade.png',
      templateData: JSON.stringify({ layout: 'table', sections: ['header', 'student-info', 'grades', 'attendance', 'comments'], styles: { primary: '#1565C0', secondary: '#1E88E5', accent: '#F44336' } }),
      colors: JSON.stringify({ primary: '#1565C0', secondary: '#1E88E5', accent: '#F44336', background: '#FFFFFF', text: '#212121' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'brochure-event-conference',
      nameAr: 'بروشور مؤتمر',
      description: 'Conference and event brochure template',
      descriptionAr: 'قالب بروشور مؤتمرات وفعاليات',
      category: 'بروشورات تسويقية',
      thumbnailUrl: '/templates/event-conference.png',
      templateData: JSON.stringify({ layout: 'event', sections: ['cover', 'schedule', 'speakers', 'venue', 'registration'], styles: { primary: '#311B92', secondary: '#7C4DFF', accent: '#FF6F00' } }),
      colors: JSON.stringify({ primary: '#311B92', secondary: '#7C4DFF', accent: '#FF6F00', background: '#EDE7F6', text: '#311B92' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'report-inventory-stock',
      nameAr: 'تقرير جرد مخزون',
      description: 'Inventory and stock management report',
      descriptionAr: 'تقرير جرد وإدارة المخزون',
      category: 'تقارير الأعمال',
      thumbnailUrl: '/templates/inventory-report.png',
      templateData: JSON.stringify({ layout: 'table', sections: ['header', 'summary', 'items', 'movements', 'alerts'], styles: { primary: '#E65100', secondary: '#FF9800', accent: '#FFF3E0' } }),
      colors: JSON.stringify({ primary: '#E65100', secondary: '#FF9800', accent: '#FFF3E0', background: '#FFFFFF', text: '#3E2723' }),
      fonts: JSON.stringify({ heading: 'Tajawal', body: 'Almarai' }),
      isPublished: true,
    },
    {
      name: 'presentation-marketing-strategy',
      nameAr: 'عرض تقديمي - استراتيجية تسويق',
      description: 'Marketing strategy presentation',
      descriptionAr: 'عرض تقديمي لاستراتيجية التسويق',
      category: 'عروض تقديمية',
      thumbnailUrl: '/templates/marketing-strategy.png',
      templateData: JSON.stringify({ layout: 'strategic', sections: ['title', 'objectives', 'market', 'channels', 'campaigns', 'budget', 'kpis'], styles: { primary: '#AD1457', secondary: '#E91E63', accent: '#F48FB1' } }),
      colors: JSON.stringify({ primary: '#AD1457', secondary: '#E91E63', accent: '#F48FB1', background: '#FFFFFF', text: '#212121' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'company-profile-creative',
      nameAr: 'ملف شركة - إبداعي',
      description: 'Creative company profile with modern design',
      descriptionAr: 'ملف تعريف شركة بتصميم إبداعي عصري',
      category: 'ملفات شركات',
      thumbnailUrl: '/templates/company-creative.png',
      templateData: JSON.stringify({ layout: 'creative', sections: ['cover', 'story', 'team', 'projects', 'clients', 'contact'], styles: { primary: '#00BFA5', secondary: '#1DE9B6', accent: '#FF9100' } }),
      colors: JSON.stringify({ primary: '#00BFA5', secondary: '#1DE9B6', accent: '#FF9100', background: '#F5F5F5', text: '#212121' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'report-risk-assessment',
      nameAr: 'تقرير تقييم مخاطر',
      description: 'Risk assessment and management report',
      descriptionAr: 'تقرير تقييم وإدارة المخاطر',
      category: 'تقارير الأعمال',
      thumbnailUrl: '/templates/risk-assessment.png',
      templateData: JSON.stringify({ layout: 'matrix', sections: ['cover', 'scope', 'risks', 'analysis', 'mitigation', 'monitoring'], styles: { primary: '#BF360C', secondary: '#FF5722', accent: '#FFAB91' } }),
      colors: JSON.stringify({ primary: '#BF360C', secondary: '#FF5722', accent: '#FFAB91', background: '#FBE9E7', text: '#3E2723' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'brochure-nonprofit',
      nameAr: 'بروشور جمعية خيرية',
      description: 'Nonprofit organization brochure template',
      descriptionAr: 'بروشور للمنظمات غير الربحية والجمعيات الخيرية',
      category: 'بروشورات تجارية',
      thumbnailUrl: '/templates/nonprofit.png',
      templateData: JSON.stringify({ layout: 'storytelling', sections: ['cover', 'mission', 'impact', 'projects', 'donate'], styles: { primary: '#00695C', secondary: '#4DB6AC', accent: '#FFD54F' } }),
      colors: JSON.stringify({ primary: '#00695C', secondary: '#4DB6AC', accent: '#FFD54F', background: '#E0F2F1', text: '#004D40' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'report-construction-progress',
      nameAr: 'تقرير تقدم أعمال - إنشاءات',
      description: 'Construction project progress report',
      descriptionAr: 'تقرير تقدم أعمال المقاولات والإنشاءات',
      category: 'تقارير مشاريع',
      thumbnailUrl: '/templates/construction.png',
      templateData: JSON.stringify({ layout: 'progress', sections: ['header', 'summary', 'schedule', 'tasks', 'materials', 'safety'], styles: { primary: '#4E342E', secondary: '#795548', accent: '#FFC107' } }),
      colors: JSON.stringify({ primary: '#4E342E', secondary: '#795548', accent: '#FFC107', background: '#FFF8E1', text: '#3E2723' }),
      fonts: JSON.stringify({ heading: 'Tajawal', body: 'Almarai' }),
      isPublished: true,
    },
    {
      name: 'presentation-research-defense',
      nameAr: 'عرض تقديمي - مناقشة بحث',
      description: 'Academic research defense presentation',
      descriptionAr: 'عرض تقديمي لمناقشة الرسائل والأبحاث',
      category: 'عروض تقديمية',
      thumbnailUrl: '/templates/research-defense.png',
      templateData: JSON.stringify({ layout: 'academic', sections: ['title', 'intro', 'literature', 'methodology', 'results', 'discussion', 'conclusion'], styles: { primary: '#1A237E', secondary: '#5C6BC0', accent: '#FFD700' } }),
      colors: JSON.stringify({ primary: '#1A237E', secondary: '#5C6BC0', accent: '#FFD700', background: '#FFFFFF', text: '#1A237E' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'cv-medical-doctor',
      nameAr: 'سيرة ذاتية - أطباء',
      description: 'Medical CV template for doctors and healthcare professionals',
      descriptionAr: 'قالب سيرة ذاتية طبية للأطباء',
      category: 'سير ذاتية',
      thumbnailUrl: '/templates/cv-medical.png',
      templateData: JSON.stringify({ layout: 'professional', sections: ['header', 'summary', 'experience', 'education', 'certifications', 'publications'], styles: { primary: '#004D40', secondary: '#00897B', accent: '#80CBC4' } }),
      colors: JSON.stringify({ primary: '#004D40', secondary: '#00897B', accent: '#80CBC4', background: '#FFFFFF', text: '#004D40' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'brochure-fitness-gym',
      nameAr: 'بروشور نادي رياضي',
      description: 'Fitness and gym membership brochure',
      descriptionAr: 'بروشور اشتراكات النوادي الرياضية',
      category: 'بروشورات تسويقية',
      thumbnailUrl: '/templates/fitness-gym.png',
      templateData: JSON.stringify({ layout: 'bold', sections: ['cover', 'programs', 'pricing', 'trainers', 'join'], styles: { primary: '#212121', secondary: '#424242', accent: '#FF6F00' } }),
      colors: JSON.stringify({ primary: '#212121', secondary: '#424242', accent: '#FF6F00', background: '#FFFFFF', text: '#212121' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'report-quality-audit',
      nameAr: 'تقرير تدقيق جودة',
      description: 'Quality assurance audit report',
      descriptionAr: 'تقرير تدقيق وضمان الجودة',
      category: 'تقارير الأعمال',
      thumbnailUrl: '/templates/quality-audit.png',
      templateData: JSON.stringify({ layout: 'audit', sections: ['title', 'scope', 'criteria', 'findings', 'score', 'recommendations'], styles: { primary: '#33691E', secondary: '#689F38', accent: '#AED581' } }),
      colors: JSON.stringify({ primary: '#33691E', secondary: '#689F38', accent: '#AED581', background: '#F1F8E9', text: '#1B5E20' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'portfolio-architect',
      nameAr: 'ملف إنجاز - معماري',
      description: 'Architecture portfolio template',
      descriptionAr: 'قالب ملف إنجاز للمهندسين المعماريين',
      category: 'ملفات إنجاز',
      thumbnailUrl: '/templates/architect-portfolio.png',
      templateData: JSON.stringify({ layout: 'gallery', sections: ['cover', 'projects', 'design', 'process', 'contact'], styles: { primary: '#3E2723', secondary: '#795548', accent: '#D7CCC8' } }),
      colors: JSON.stringify({ primary: '#3E2723', secondary: '#795548', accent: '#D7CCC8', background: '#FFFFFF', text: '#3E2723' }),
      fonts: JSON.stringify({ heading: 'Tajawal', body: 'Almarai' }),
      isPublished: true,
    },
    {
      name: 'presentation-board-meeting',
      nameAr: 'عرض تقديمي - مجلس إدارة',
      description: 'Board of directors meeting presentation',
      descriptionAr: 'عرض تقديمي لاجتماعات مجلس الإدارة',
      category: 'عروض تقديمية',
      thumbnailUrl: '/templates/board-meeting.png',
      templateData: JSON.stringify({ layout: 'formal', sections: ['title', 'agenda', 'financials', 'strategy', 'decisions', 'next-steps'], styles: { primary: '#1A237E', secondary: '#303F9F', accent: '#FFD700' } }),
      colors: JSON.stringify({ primary: '#1A237E', secondary: '#303F9F', accent: '#FFD700', background: '#FFFFFF', text: '#1A237E' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'brochure-beauty-spa',
      nameAr: 'بروشور سبا وتجميل',
      description: 'Beauty salon and spa services brochure',
      descriptionAr: 'بروشور خدمات التجميل والسبا',
      category: 'بروشورات تسويقية',
      thumbnailUrl: '/templates/beauty-spa.png',
      templateData: JSON.stringify({ layout: 'elegant', sections: ['cover', 'services', 'packages', 'gallery', 'booking'], styles: { primary: '#880E4F', secondary: '#C2185B', accent: '#F8BBD0' } }),
      colors: JSON.stringify({ primary: '#880E4F', secondary: '#C2185B', accent: '#F8BBD0', background: '#FCE4EC', text: '#4A0024' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'report-logistics-supply-chain',
      nameAr: 'تقرير لوجستي - سلسلة توريد',
      description: 'Logistics and supply chain report',
      descriptionAr: 'تقرير الخدمات اللوجستية وسلسلة التوريد',
      category: 'تقارير الأعمال',
      thumbnailUrl: '/templates/logistics.png',
      templateData: JSON.stringify({ layout: 'dashboard', sections: ['summary', 'inventory', 'shipments', 'warehouses', 'costs'], styles: { primary: '#0D47A1', secondary: '#1976D2', accent: '#64B5F6' } }),
      colors: JSON.stringify({ primary: '#0D47A1', secondary: '#1976D2', accent: '#64B5F6', background: '#FFFFFF', text: '#0D47A1' }),
      fonts: JSON.stringify({ heading: 'Tajawal', body: 'Almarai' }),
      isPublished: true,
    },
    {
      name: 'cv-engineering',
      nameAr: 'سيرة ذاتية - مهندسين',
      description: 'Engineering CV template for engineers',
      descriptionAr: 'قالب سيرة ذاتية للمهندسين',
      category: 'سير ذاتية',
      thumbnailUrl: '/templates/cv-engineering.png',
      templateData: JSON.stringify({ layout: 'technical', sections: ['header', 'summary', 'experience', 'projects', 'skills', 'education'], styles: { primary: '#37474F', secondary: '#546E7A', accent: '#FFB300' } }),
      colors: JSON.stringify({ primary: '#37474F', secondary: '#546E7A', accent: '#FFB300', background: '#FFFFFF', text: '#263238' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'report-social-media-analytics',
      nameAr: 'تقرير تحليلات تواصل اجتماعي',
      description: 'Social media analytics and performance report',
      descriptionAr: 'تقرير تحليلات أداء وسائل التواصل الاجتماعي',
      category: 'تقارير تسويق',
      thumbnailUrl: '/templates/social-analytics.png',
      templateData: JSON.stringify({ layout: 'analytics', sections: ['summary', 'platforms', 'engagement', 'content', 'growth', 'recommendations'], styles: { primary: '#006064', secondary: '#00ACC1', accent: '#FF6F00' } }),
      colors: JSON.stringify({ primary: '#006064', secondary: '#00ACC1', accent: '#FF6F00', background: '#FFFFFF', text: '#006064' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'presentation-software-demo',
      nameAr: 'عرض تقديمي - شرح برنامج',
      description: 'Software product demo and walkthrough presentation',
      descriptionAr: 'عرض تقديمي لشرح وعرض البرامج',
      category: 'عروض تقديمية',
      thumbnailUrl: '/templates/software-demo.png',
      templateData: JSON.stringify({ layout: 'demo', sections: ['title', 'overview', 'features', 'demo', 'pricing', 'faq'], styles: { primary: '#283593', secondary: '#5C6BC0', accent: '#00E676' } }),
      colors: JSON.stringify({ primary: '#283593', secondary: '#5C6BC0', accent: '#00E676', background: '#FFFFFF', text: '#1A237E' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'brochure-education-course',
      nameAr: 'بروشور دورة تدريبية',
      description: 'Educational course and training program brochure',
      descriptionAr: 'بروشور للدورات التدريبية والبرامج التعليمية',
      category: 'بروشورات تسويقية',
      thumbnailUrl: '/templates/education-course.png',
      templateData: JSON.stringify({ layout: 'educational', sections: ['cover', 'overview', 'curriculum', 'instructors', 'pricing', 'register'], styles: { primary: '#01579B', secondary: '#0288D1', accent: '#81D4FA' } }),
      colors: JSON.stringify({ primary: '#01579B', secondary: '#0288D1', accent: '#81D4FA', background: '#FFFFFF', text: '#01579B' }),
      fonts: JSON.stringify({ heading: 'Tajawal', body: 'Almarai' }),
      isPublished: true,
    },
    {
      name: 'report-csr-sustainability',
      nameAr: 'تقرير المسؤولية المجتمعية',
      description: 'Corporate social responsibility and sustainability report',
      descriptionAr: 'تقرير المسؤولية المجتمعية والاستدامة',
      category: 'تقارير الأعمال',
      thumbnailUrl: '/templates/csr-report.png',
      templateData: JSON.stringify({ layout: 'modern', sections: ['cover', 'ceo-message', 'initiatives', 'impact', 'goals', 'partners'], styles: { primary: '#1B5E20', secondary: '#388E3C', accent: '#A5D6A7' } }),
      colors: JSON.stringify({ primary: '#1B5E20', secondary: '#388E3C', accent: '#A5D6A7', background: '#F1F8E9', text: '#1B5E20' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'portfolio-interior-design',
      nameAr: 'ملف إنجاز - تصميم داخلي',
      description: 'Interior design portfolio template',
      descriptionAr: 'قالب ملف إنجاز للمصممين الداخليين',
      category: 'ملفات إنجاز',
      thumbnailUrl: '/templates/interior-portfolio.png',
      templateData: JSON.stringify({ layout: 'gallery', sections: ['cover', 'projects', 'process', 'services', 'contact'], styles: { primary: '#4E342E', secondary: '#8D6E63', accent: '#D7CCC8' } }),
      colors: JSON.stringify({ primary: '#4E342E', secondary: '#8D6E63', accent: '#D7CCC8', background: '#FAFAFA', text: '#3E2723' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
    {
      name: 'presentation-team-meeting',
      nameAr: 'عرض تقديمي - اجتماع فريق',
      description: 'Weekly team meeting presentation template',
      descriptionAr: 'عرض تقديمي لاجتماعات الفريق الأسبوعية',
      category: 'عروض تقديمية',
      thumbnailUrl: '/templates/team-meeting.png',
      templateData: JSON.stringify({ layout: 'simple', sections: ['title', 'updates', 'blockers', 'goals', 'actions'], styles: { primary: '#455A64', secondary: '#607D8B', accent: '#FF5722' } }),
      colors: JSON.stringify({ primary: '#455A64', secondary: '#607D8B', accent: '#FF5722', background: '#FFFFFF', text: '#263238' }),
      fonts: JSON.stringify({ heading: 'Cairo', body: 'Noto Sans Arabic' }),
      isPublished: true,
    },
  ];

  for (const template of templates) {
    await prisma.template.upsert({
      where: { id: template.name },
      update: {},
      create: {
        id: template.name,
        name: template.name,
        nameAr: template.nameAr,
        description: template.description,
        descriptionAr: template.descriptionAr,
        category: template.category,
        thumbnailUrl: template.thumbnailUrl,
        templateData: template.templateData,
        colors: template.colors,
        fonts: template.fonts,
        isPublished: true,
      },
    });
  }

  const demoProjects = [
    { title: 'تقرير يوم التأسيس السعودي', description: 'تقرير شامل عن تاريخ المملكة العربية السعودية بمناسبة يوم التأسيس', projectType: 'REPORT', status: 'COMPLETED', content: JSON.stringify({ body: 'تأسست المملكة العربية السعودية على يد الملك عبدالعزيز بن عبدالرحمن آل سعود عام 1902 عندما استرد الرياض. ومنذ ذلك الحين شهدت المملكة تطوراً كبيراً في جميع المجالات. يعتبر يوم التأسيس مناسبة وطنية مهمة تحيي ذكرى تأسيس الدولة السعودية الأولى قبل ثلاثة قرون.' }) },
    { title: 'بروشور الأمن السيبراني', description: 'بروشور تعريفي عن أهمية الأمن السيبراني وطرق الحماية', projectType: 'BROCHURE', status: 'COMPLETED', content: JSON.stringify({ body: 'الأمن السيبراني هو مجموعة من الممارسات والتقنيات المصممة لحماية الأنظمة والشبكات والبرامج من الهجمات الرقمية. تشمل أهم ممارسات الأمن السيبراني: استخدام كلمات مرور قوية، تحديث البرامج باستمرار، تفعيل المصادقة الثنائية، الحذر من رسائل التصيد.' }) },
    { title: 'عرض تقديمي لمشروع التخرج', description: 'عرض تقديمي شامل لمشروع تخرج في نظم المعلومات', projectType: 'PRESENTATION', status: 'DRAFT', content: JSON.stringify({ body: 'مشروع التخرج: تطبيق ذكي لإدارة المشاريع باستخدام تقنيات الذكاء الاصطناعي. يهدف المشروع إلى تسهيل إدارة المهام وتتبع التقدم وإعداد التقارير الآلية.' }) },
    { title: 'تقرير المبيعات الربع سنوي', description: 'تحليل أداء المبيعات للربع الأول من العام', projectType: 'REPORT', status: 'COMPLETED', content: JSON.stringify({ body: 'سجلت المبيعات في الربع الأول نمواً بنسبة 25% مقارنة بالربع الماضي. بلغ إجمالي الإيرادات 2.5 مليون ريال. تصدر منتجنا الرئيسي قائمة المبيعات بحصة 40% من إجمالي الإيرادات.' }) },
    { title: 'بروشور الشركة التعريفي', description: 'بروشور تعريفي بالشركة وخدماتها', projectType: 'BROCHURE', status: 'COMPLETED', content: JSON.stringify({ body: 'شركة متخصصة في تقديم حلول تقنية مبتكرة للشركات. نقدم خدماتنا في مجالات: تطوير البرمجيات، الذكاء الاصطناعي، تحليل البيانات، الاستشارات التقنية. تأسست الشركة عام 2020 وخدمت أكثر من 100 عميل.' }) },
    { title: 'خطة تسويقية للمنتج الجديد', description: 'خطة تسويقية شاملة لإطلاق منتج جديد', projectType: 'REPORT', status: 'DRAFT', content: JSON.stringify({ body: 'الخطة التسويقية للمنتج الجديد تهدف إلى تحقيق انتشار في السوق المستهدف خلال 6 أشهر. تشمل الاستراتيجية: الحملات الرقمية، التسويق عبر المؤثرين، العروض الترويجية، وتحسين محركات البحث.' }) },
    { title: 'تقرير الأداء السنوي', description: 'تقرير أداء الشركة السنوي للعام المالي', projectType: 'REPORT', status: 'COMPLETED', content: JSON.stringify({ body: 'حققنا في هذا العام إنجازات كبيرة: نمو في الإيرادات بنسبة 35%، توسع في 3 أسواق جديدة، إطلاق 5 منتجات مبتكرة، وزيادة فريق العمل بنسبة 50%. نشكر جميع شركائنا وعملائنا على ثقتهم.' }) },
  ];

  for (const demo of demoProjects) {
    await prisma.project.create({
      data: {
        userId: admin.id,
        title: demo.title,
        description: demo.description,
        projectType: demo.projectType,
        status: demo.status,
        content: demo.content,
        generatedContent: demo.content,
        wordCount: JSON.parse(demo.content).body.length,
        sharedLink: `demo-${demo.title.replace(/\s+/g, '-').toLowerCase()}-${Date.now()}`,
      },
    });
  }

  const activityActions = ['CREATE_PROJECT', 'EDIT_PROJECT', 'EXPORT_PROJECT', 'LOGIN', 'UPDATE_PROFILE', 'VIEW_TEMPLATES', 'CREATE_PROJECT', 'EXPORT_PROJECT', 'LOGIN', 'EDIT_PROJECT'];
  for (const action of activityActions) {
    await prisma.activityLog.create({
      data: {
        userId: admin.id,
        action,
        details: JSON.stringify({ timestamp: new Date().toISOString(), info: `تم تنفيذ الإجراء: ${action}` }),
      },
    });
  }

  console.log('Seed data created successfully');
  console.log(`Admin email: nwrah3647@gmail.com`);
  console.log(`Admin password: Nwrah@123`);
  console.log(`Templates created: ${templates.length}`);
  console.log(`Demo projects created: ${demoProjects.length}`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
